"""
Django settings for szkolnabiblioteka_v1 project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fzpr!lol51d*w=czbevbb$j2z*6nwkgjb_qe%ue05r1ed%&3ad'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


ALLOWED_HOSTS = ['127.0.0.1','localhost','bibliotekademo.herokuapp.com']
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'books',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django_auto_logout.middleware.auto_logout',
]

ROOT_URLCONF = 'szkolnabiblioteka_v1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['books/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'szkolnabiblioteka_v1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
#

# # Biblioteka dla Studzienca
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#
#         'NAME': 'd9ae8hri40h06c',
#         'USER': 'gqduhagmsgophv',
#         'PASSWORD': '192fab0ba0798500cb7ea0e9a083f9f2fd6642d363a4a70d767b0c3886b67e41',
#         'HOST': 'ec2-52-214-178-113.eu-west-1.compute.amazonaws.com',
#         'PORT': '5432',
#     }
# }
#

# Biblioteka demo


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',

        'NAME': 'da1usktkanjqe7',
        'USER': 'jhxyismgohtttm',
        'PASSWORD': 'ad0138d3489d6a98dbd244d3a45ba8e87c123967cc6bdf1d151f815291f170ef',
        'HOST': 'ec2-18-202-156-92.eu-west-1.compute.amazonaws.com',
        'PORT': '5432',
    }
}

# Biblioteka na localhost
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#
#         'NAME': 'biblioteka',
#         'USER': 'bibliotekauser',
#         'PASSWORD': 'user123',
#         'HOST': 'localhost',
#         'PORT': '',
#     }
# }
#
#

#################### MYSQL###############
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'butek$bibliotekademo',
#         'USER': 'butek',
#         'PASSWORD': 'komiX123',
#         'HOST': 'butek.mysql.pythonanywhere-services.com',
#     }
# }






# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': str(BASE_DIR / 'db.sqlite3'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
# #
# if DEBUG:
#    # STATIC_ROOT = os.path.join(BASE_DIR, '/media/')
#    STATIC_ROOT = '/media/'
# else:
#     STATIC_ROOT = os.path.join(BASE_DIR, 'media')
# STATIC_URL = '/media/'
# # # STATIC_ROOT = os.path.join(BASE_DIR, '/static/')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# xxxxxxxxxxxxxxxxxxx
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
#xxxxxxxxxxxxxxxxxxxx





#
# if DEBUG:
#     STATICFILES_DIRS=[os.path.join(BASE_DIR, 'static')]
# else:
#     STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# MEDIA_ROOT = [os.path.join(BASE_DIR, 'media')]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#
# # Redirected po wylogowaniu z panelu admina
LOGOUT_REDIRECT_URL = '/'
# # wylogowanie po zamknieciu przegladarki
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#
# SESSION_COOKIE_DOMAIN = 'bibliotekademo.herokuapp.com'
AUTO_LOGOUT = {'IDLE_TIME': 600}